

# ??????? ????? ????????? ? application.yaml
spring.profiles.active: some
# ???? application.yaml ?? ??????????, ?? ???? application-{profile}.yaml, ?? ????? ??????? ??????? ???-?? ??? (????????, ??? ?????? ???????? ??? ???????, ????? ????? ??????)
# ???????? ????: ??? ?????????? ?????????? application.yaml ????????????? ????????? ??????. ? ?????????? ??????? ? ?????: java -jar app.jar --spring.profiles.active=another ? ??? ?????????? (application-another.yaml ???????? ??? ??????????? ????????)

val:
  1: Apple
  2: Banana # ???????? ????? ??????????, ??? ??? ? ?????? ????? ???? ????? ??????????? val.2
  3: Cucumber

#word: world    # // ???? ??? ???????? ??????, ????? ??????, ?? ? ?????? ?????? ??? - word ????????? ? ?????? ?????.