spring:
  datasource:
    #url: "jdbc:h2:mem:"                        # in memory mode (by default)
    url: "jdbc:h2:~/test"                      # embedded mode
    #url: "jdbc:h2:tcp://localhost/C:/Users/Solibr/test"       # server mode
    username: "sa"
    password: ""


# these properties only provides creation of creare.sql file
#spring.jpa.properties.javax.persistence.schema-generation.scripts.action: create
#spring.jpa.properties.javax.persistence.schema-generation.scripts.create-target: create.sql
#spring.jpa.properties.javax.persistence.schema-generation.scripts.create-source: metadata

#spring.jpa.generate-ddl: true
spring.jpa.hibernate.ddl-auto: update